#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TBI-NeuroHELM paper figure/table generator, v7 submission-ready edition.

This script intentionally does NOT generate Figure 1 or Figure 2.

Direct MedHELM public-code adaptations:
- Figure 3: benchmark heatmap, adapted from MedHELM heatmap code.
- Figure 4: category heatmap, adapted from MedHELM aggregated heatmap code.
- Figure 5: cost vs mean win rate, adapted from MedHELM cost plot code.
- Table 1: win-rate leaderboard, adapted from MedHELM win-rate table code.

TBI-specific outputs written in the same reporting/visual style:
- Supplementary Figure 1 (raw generator name: extended_data_fig1): subcategory heatmap.
- Supplementary Figure 2 (raw generator name: supplementary_fig1): LLM-jury robustness and stability.
- Supplementary Table 1 (raw generator name: extended_data_table1): benchmark suite inventory.
- Supplementary Table 2 (raw generator name: supplementary_table1): instance distribution.
- Supplementary Table 3 (raw generator name: supplementary_table2): model registry and run configuration.
- Supplementary Table 4 (raw generator name: supplementary_table3): open-task scoring dimensions.
- Supplementary Table 6 (raw generator name: supplementary_table4): jury-combination robustness.
- Supplementary Table 7 (raw generator name: extended_data_table2): model-level cost and performance.

Supplementary Tables 5, 8, and 9 are manuscript/supplementary workbooks that are
handled as separate submission assets rather than generated by this plotting script.
Internal QC/readiness files are retained under internal_qc/ but are not numbered as formal supplementary tables.
"""
from __future__ import annotations

import argparse
import importlib
from pathlib import Path
import sys

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from tbi_neurohelm.common import ensure_output_dirs, validate_final_qc

heatmaps = importlib.import_module("tbi_neurohelm.plots.reference_heatmaps_tbi")
costs = importlib.import_module("tbi_neurohelm.plots.reference_costs_tbi")
supp_figs = importlib.import_module("tbi_neurohelm.plots.custom_supplementary_figures_tbi")
win_table = importlib.import_module("tbi_neurohelm.tables.reference_win_rate_table_tbi")
custom_tables = importlib.import_module("tbi_neurohelm.tables.custom_reference_style_tables_tbi")


def _validate_input_dir(input_dir: Path) -> Path:
    input_dir = input_dir.resolve()
    if not input_dir.is_dir():
        raise NotADirectoryError(f"Input path is not a directory: {input_dir}")
    if not (input_dir / "07_leaderboard.csv").exists():
        raise FileNotFoundError(
            f"{input_dir} does not look like the final tbi_neurohelm_outputs folder; "
            "07_leaderboard.csv was not found. Unzip the results first and pass the inner folder."
        )
    return input_dir


def _write_artifact_index(output_dir: Path) -> None:
    rows: list[dict[str, object]] = []
    for p in sorted(output_dir.rglob("*")):
        if p.is_file() and p.name != "artifact_index.csv":
            rows.append({
                "relative_path": p.relative_to(output_dir).as_posix(),
                "suffix": p.suffix.lower(),
                "size_bytes": p.stat().st_size,
            })
    pd.DataFrame(rows).to_csv(output_dir / "artifact_index.csv", index=False)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate TBI-NeuroHELM figures/tables in MedHELM-matched style.")
    parser.add_argument("--input_dir", required=True, type=Path, help="Path to the unzipped final tbi_neurohelm_outputs folder")
    parser.add_argument("--output_dir", required=True, type=Path, help="Directory for paper artifacts")
    parser.add_argument("--strict_qc", action="store_true", help="Abort unless the run is clean enough for final figures/tables")
    args = parser.parse_args()

    input_dir = _validate_input_dir(args.input_dir)
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    figures, tables, _source = ensure_output_dirs(output_dir)
    qc = validate_final_qc(input_dir, strict=args.strict_qc)
    qc.to_csv(output_dir / "qc_check_for_figure_generation.csv", index=False)

    # Reference-code adaptations.
    heatmaps.make_reference_heatmaps(input_dir, figures)
    costs.plot_cost_vs_win_rate(input_dir, figures / "fig5_cost_vs_mean_win_rate")
    win_table.write_table(input_dir, tables / "table1_win_rate_leaderboard")

    # Reference-style, TBI-specific additions.
    custom_tables.extended_data_table1_benchmark_suite(input_dir, tables / "extended_data_table1_benchmark_suite")
    custom_tables.extended_data_table2_cost_performance(input_dir, tables / "extended_data_table2_cost_performance")
    supp_figs.plot_supplementary_fig1_jury_robustness(input_dir, figures / "supplementary_fig1_jury_robustness")
    custom_tables.supplementary_table1_instance_distribution(input_dir, tables / "supplementary_table1_instance_distribution")
    custom_tables.supplementary_table2_model_registry_and_run_config(input_dir, tables / "supplementary_table2_model_registry_and_run_config")
    custom_tables.supplementary_table3_open_task_dimensions(input_dir, tables / "supplementary_table3_open_task_dimensions")
    custom_tables.supplementary_table4_jury_combination_robustness(input_dir, tables / "supplementary_table4_jury_combination_robustness")
    custom_tables.write_internal_qc_artifacts(input_dir, output_dir)

    _write_artifact_index(output_dir)

    print(f"Done. Artifacts written to: {output_dir}")
    print(f"QC summary: {output_dir / 'qc_check_for_figure_generation.csv'}")
    print(f"Artifact index: {output_dir / 'artifact_index.csv'}")


if __name__ == "__main__":
    main()
    # Some matplotlib/PDF backends can keep non-daemon helper threads alive on
    # certain desktop Python installations after all files have been written.
    # Force a clean process exit only after successful completion.
    import os
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(0)
